import math
print("pi value=",math.pi)
print("e value=",math.e)
print("radians value=",math.radians(int(input("enter number for radians"))))
print("sin value=",math.sin(int(input("enter number for sin"))))
print("cos value=",math.cos(int(input("enter number for cos"))))
print("tan value=",math.tan(int(input("enter number for tan"))))
print("log value=",math.log(int(input("enter number for log"))))
print("log10 value=",math.log10(int(input("enter number for log10"))))
print("exp value=",math.exp(int(input("enter number for exp"))))
print("e** value=",math.e**(int(input("enter number for e**"))))
print("power value=",math.pow(2,4))
print("sqrt value=",math.sqrt(int(input("enter number for sqrt"))))
print("floor value=",math.floor(int(input("enter number for floor"))))
print("ceil value=",math.ceil(float(input("enter number for ceil"))))